### PR TITLE
fix(aztec.js): fix node build

### LINKED ISSUE #536: Note.derive not setting owner
## Expected Behaviour

When creating a note from an event log, the `owner` property should be set so it can be used in a JoinSplit proof.

```js
const note = require("aztec.js").note
const secp256k1 = require("@aztec/secp256k1")
const metadata = "0x1c6a72f049e538bb2c272529d626245da8e4380b3b78a848e7f35d54b6c4e7da27a387ec17338eefe6ab0c287807df0fd4437a3ad83190e0195e13505b609110dd6feecda50f75d733cf956c57e786976af334a9670c9dc27ce90139db3d1cf901"
const account = secp256k1.accountFromPrivateKey(
  "0x0000000000000000000000000000000000000000000000000000000000000003"
)
note.fromEventLog(
  metadata,
  account.privateKey
).then(note1 => {
  console.log(`Note owner ${note1.owner}`)
})
```

## Current Behaviour

The following error is thrown when the JoinSplit proof is sent to the zkAsset in a `confidentialTransfer` transaction
```
revert input note owner does not match
```

## Possible Solution

My current workaround is to explicitly set the `owner` property after the note is created and before the note is used in a JoinSplit proof. For example in the above, `note1.owner = account.address`. This allows the `confidentialTransfer` transaction to succeed.

I think the better solution is for `note.derive(spendingKey)` to set to `owner` property.
https://github.com/AztecProtocol/AZTEC/blob/bad7b4bd24a7bb07968e2c7b15af750b920618ec/packages/aztec.js/src/note/index.js#L116

## Your Environment

-   AZTEC packages and their versions: aztec.js 0.18.0
-   Node and yarn version: node v12.11.1

### PR DESCRIPTION
**Pull request by ArnSch**
## Summary

Fixes #536 and #535. Explicitly includes `mcl.wasm` in node build of `aztec.js`, and populates owner field of notes recovered from event logs.

## Testing instructions

`yarn test`

## Types of changes

* Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: packages/aztec.js/src/note/index.js [hunk 1]
```diff
@@ -307,10 +307,12 @@ export function encodeMetadata(noteArray) {
...
  */
 export async function fromEventLog(logNoteData, spendingKey = null) {
-    const publicKey = noteCoder.decodeNoteFromEventLog(logNoteData);
-    const newNote = new Note(publicKey, null);
+    const notePublicKey = noteCoder.decodeNoteFromEventLog(logNoteData);
+    const newNote = new Note(notePublicKey, null);
     if (spendingKey) {
         await newNote.derive(spendingKey);
+        const { publicKey } = secp256k1.accountFromPrivateKey(spendingKey);
+        newNote.owner = publicKey;
```
Comment (thomas-waite) [inline packages/aztec.js/src/note/index.js]: I think the note owner is the Ethereum address of the owning account rather than `publicKey`? On the `note` class:
```
        /**
         * Ethereum address of note's owner
         * @member {string}
         */
        this.owner = owner;
```

**Review by thomas-waite — CHANGES_REQUESTED** [review]
Question about the `note.owner` set. @joeandrews  knows more about webpack than I do, but looks reasonable

File: packages/aztec.js/src/note/index.js (hunk 1 above)
Comment (ArnSch) [reply packages/aztec.js/src/note/index.js]: Ah, good catch!

**Comment by ArnSch** [comment]
:tada: This PR is included in version 0.18.1 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by ArnSch** [comment]
:tada: This PR is included in version 1.7.1 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by ArnSch** [comment]
:tada: This PR is included in version 1.12.0 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:
